DROP TABLE IF EXISTS recipe;

CREATE TABLE recipe (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  picture VARCHAR(250) NOT NULL DEFAULT 'grilled_peas.png',
  title VARCHAR(25) NOT NULL,
  difficulty INT NOT NULL,
  time VARCHAR(10) NOT NULL
);